# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/HLS/softmax2/solution1/impl/ip/tmp.srcs/sources_1/ip/softmax1_dexp_64ns_64ns_64_18_full_dsp_1_ip/softmax1_dexp_64ns_64ns_64_18_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==softmax1_dexp_64ns_64ns_64_18_full_dsp_1_ip || ORIG_REF_NAME==softmax1_dexp_64ns_64ns_64_18_full_dsp_1_ip} -quiet] -quiet

# IP: C:/HLS/softmax2/solution1/impl/ip/tmp.srcs/sources_1/ip/softmax1_sitodp_32ns_64_6_no_dsp_1_ip/softmax1_sitodp_32ns_64_6_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==softmax1_sitodp_32ns_64_6_no_dsp_1_ip || ORIG_REF_NAME==softmax1_sitodp_32ns_64_6_no_dsp_1_ip} -quiet] -quiet
