// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ReLU_ReLU,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.425083,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=138,HLS_SYN_LUT=1382,HLS_VERSION=2021_2}" *)

module ReLU (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] x;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [63:0] grp_fu_66_p1;
reg   [63:0] y_assign_reg_292;
wire    ap_CS_fsm_state6;
reg   [0:0] p_Result_s_reg_299;
wire    ap_CS_fsm_state7;
wire   [51:0] tmp_5_fu_173_p1;
reg   [51:0] tmp_5_reg_304;
wire   [0:0] isNeg_fu_187_p3;
reg   [0:0] isNeg_reg_309;
wire   [11:0] ush_fu_205_p3;
reg   [11:0] ush_reg_314;
wire   [63:0] data_V_fu_70_p1;
wire   [10:0] tmp_2_fu_73_p4;
wire   [51:0] tmp_3_fu_83_p1;
wire   [0:0] icmp_ln1018_fu_87_p2;
wire   [0:0] icmp_ln1018_1_fu_93_p2;
wire   [0:0] ymaggreater_fu_117_p2;
wire   [0:0] and_ln25_fu_99_p2;
wire   [63:0] res_fu_123_p3;
wire   [0:0] icmp_ln1018_2_fu_105_p2;
wire   [0:0] xor_ln1022_fu_111_p2;
wire   [63:0] select_ln25_fu_130_p3;
wire   [0:0] and_ln18_fu_137_p2;
wire   [63:0] bitcast_ln486_fu_143_p1;
wire   [63:0] data_V_1_fu_147_p3;
wire   [10:0] tmp_4_fu_163_p4;
wire   [11:0] zext_ln513_fu_177_p1;
wire   [11:0] add_ln513_fu_181_p2;
wire   [10:0] sub_ln1364_fu_195_p2;
wire  signed [11:0] sext_ln1364_fu_201_p1;
wire    ap_CS_fsm_state8;
wire   [53:0] mantissa_fu_213_p4;
wire  signed [31:0] sext_ln1340_fu_226_p1;
wire   [136:0] zext_ln15_fu_222_p1;
wire   [136:0] zext_ln1340_fu_229_p1;
wire   [136:0] r_V_fu_233_p2;
wire   [0:0] tmp_fu_245_p3;
wire   [136:0] r_V_1_fu_239_p2;
wire   [31:0] zext_ln671_fu_253_p1;
wire   [31:0] tmp_1_fu_257_p4;
wire   [31:0] val_fu_267_p3;
wire   [31:0] result_V_2_fu_274_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

ReLU_sitodp_32ns_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_6_no_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x),
    .ce(1'b1),
    .dout(grp_fu_66_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        isNeg_reg_309 <= add_ln513_fu_181_p2[32'd11];
        p_Result_s_reg_299 <= data_V_1_fu_147_p3[32'd63];
        tmp_5_reg_304 <= tmp_5_fu_173_p1;
        ush_reg_314 <= ush_fu_205_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        y_assign_reg_292 <= grp_fu_66_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln513_fu_181_p2 = ($signed(zext_ln513_fu_177_p1) + $signed(12'd3073));

assign and_ln18_fu_137_p2 = (xor_ln1022_fu_111_p2 & icmp_ln1018_2_fu_105_p2);

assign and_ln25_fu_99_p2 = (icmp_ln1018_fu_87_p2 & icmp_ln1018_1_fu_93_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign ap_return = ((p_Result_s_reg_299[0:0] == 1'b1) ? result_V_2_fu_274_p2 : val_fu_267_p3);

assign bitcast_ln486_fu_143_p1 = select_ln25_fu_130_p3;

assign data_V_1_fu_147_p3 = ((and_ln18_fu_137_p2[0:0] == 1'b1) ? 64'd0 : bitcast_ln486_fu_143_p1);

assign data_V_fu_70_p1 = y_assign_reg_292;

assign icmp_ln1018_1_fu_93_p2 = ((tmp_3_fu_83_p1 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln1018_2_fu_105_p2 = ((tmp_2_fu_73_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln1018_fu_87_p2 = ((tmp_2_fu_73_p4 == 11'd0) ? 1'b1 : 1'b0);

assign isNeg_fu_187_p3 = add_ln513_fu_181_p2[32'd11];

assign mantissa_fu_213_p4 = {{{{1'd1}, {tmp_5_reg_304}}}, {1'd0}};

assign r_V_1_fu_239_p2 = zext_ln15_fu_222_p1 << zext_ln1340_fu_229_p1;

assign r_V_fu_233_p2 = zext_ln15_fu_222_p1 >> zext_ln1340_fu_229_p1;

assign res_fu_123_p3 = ((ymaggreater_fu_117_p2[0:0] == 1'b1) ? y_assign_reg_292 : 64'd0);

assign result_V_2_fu_274_p2 = (32'd0 - val_fu_267_p3);

assign select_ln25_fu_130_p3 = ((and_ln25_fu_99_p2[0:0] == 1'b1) ? y_assign_reg_292 : res_fu_123_p3);

assign sext_ln1340_fu_226_p1 = $signed(ush_reg_314);

assign sext_ln1364_fu_201_p1 = $signed(sub_ln1364_fu_195_p2);

assign sub_ln1364_fu_195_p2 = (11'd1023 - tmp_4_fu_163_p4);

assign tmp_1_fu_257_p4 = {{r_V_1_fu_239_p2[84:53]}};

assign tmp_2_fu_73_p4 = {{data_V_fu_70_p1[62:52]}};

assign tmp_3_fu_83_p1 = data_V_fu_70_p1[51:0];

assign tmp_4_fu_163_p4 = {{data_V_1_fu_147_p3[62:52]}};

assign tmp_5_fu_173_p1 = data_V_1_fu_147_p3[51:0];

assign tmp_fu_245_p3 = r_V_fu_233_p2[32'd53];

assign ush_fu_205_p3 = ((isNeg_fu_187_p3[0:0] == 1'b1) ? sext_ln1364_fu_201_p1 : add_ln513_fu_181_p2);

assign val_fu_267_p3 = ((isNeg_reg_309[0:0] == 1'b1) ? zext_ln671_fu_253_p1 : tmp_1_fu_257_p4);

assign xor_ln1022_fu_111_p2 = (icmp_ln1018_1_fu_93_p2 ^ 1'd1);

assign ymaggreater_fu_117_p2 = (($signed(data_V_fu_70_p1) > $signed(64'd0)) ? 1'b1 : 1'b0);

assign zext_ln1340_fu_229_p1 = $unsigned(sext_ln1340_fu_226_p1);

assign zext_ln15_fu_222_p1 = mantissa_fu_213_p4;

assign zext_ln513_fu_177_p1 = tmp_4_fu_163_p4;

assign zext_ln671_fu_253_p1 = tmp_fu_245_p3;

endmodule //ReLU
