// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Softmax_Softmax,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.059000,HLS_SYN_LAT=131,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2846,HLS_SYN_LUT=3809,HLS_VERSION=2021_2}" *)

module Softmax (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        y_address0,
        y_ce0,
        y_we0,
        y_d0,
        y_q0,
        y_address1,
        y_ce1,
        y_q1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] x_address0;
output   x_ce0;
input  [63:0] x_q0;
output  [3:0] y_address0;
output   y_ce0;
output   y_we0;
output  [63:0] y_d0;
input  [63:0] y_q0;
output  [3:0] y_address1;
output   y_ce1;
input  [63:0] y_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] y_address0;
reg y_ce0;
reg y_we0;
reg[63:0] y_d0;
reg y_ce1;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
reg   [63:0] y_load_reg_90;
wire    ap_CS_fsm_state4;
wire   [63:0] b_y_fu_71_p1;
reg   [63:0] b_y_reg_95;
wire    ap_CS_fsm_state5;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_idle;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_ready;
wire   [3:0] grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_address0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_ce0;
wire   [3:0] grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0;
wire   [63:0] grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start;
wire    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done;
wire    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_idle;
wire    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_ready;
wire   [3:0] grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0;
wire   [63:0] grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out;
wire    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out_ap_vld;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_idle;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_ready;
wire   [3:0] grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0;
wire   [63:0] grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0;
wire   [3:0] grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address1;
wire    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1;
reg    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg = 1'b0;
#0 grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg = 1'b0;
#0 grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg = 1'b0;
end

Softmax_Softmax_Pipeline_VITIS_LOOP_10_1 grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start),
    .ap_done(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done),
    .ap_idle(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_idle),
    .ap_ready(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_ready),
    .x_address0(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_address0),
    .x_ce0(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_ce0),
    .x_q0(x_q0),
    .y_address0(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0),
    .y_ce0(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0),
    .y_we0(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0),
    .y_d0(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0)
);

Softmax_Softmax_Pipeline_VITIS_LOOP_14_2 grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start),
    .ap_done(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done),
    .ap_idle(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_idle),
    .ap_ready(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_ready),
    .b_y(b_y_reg_95),
    .y_address0(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0),
    .y_ce0(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0),
    .y_q0(y_q0),
    .b_y_1_out(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out),
    .b_y_1_out_ap_vld(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out_ap_vld)
);

Softmax_Softmax_Pipeline_VITIS_LOOP_17_3 grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start),
    .ap_done(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done),
    .ap_idle(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_idle),
    .ap_ready(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_ready),
    .y_address0(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0),
    .y_ce0(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0),
    .y_we0(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0),
    .y_d0(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0),
    .y_address1(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address1),
    .y_ce1(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1),
    .y_q1(y_q1),
    .b_y_1_reload(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_ready == 1'b1)) begin
            grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_ready == 1'b1)) begin
            grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg <= 1'b1;
        end else if ((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_ready == 1'b1)) begin
            grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        b_y_reg_95 <= b_y_fu_71_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        y_load_reg_90 <= y_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        y_address0 = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        y_address0 = grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_address0 = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0;
    end else begin
        y_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        y_ce0 = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        y_ce0 = grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_ce0 = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0;
    end else begin
        y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_ce1 = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1;
    end else begin
        y_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_d0 = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_d0 = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0;
    end else begin
        y_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_we0 = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y_we0 = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0;
    end else begin
        y_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign b_y_fu_71_p1 = y_load_reg_90;

assign grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg;

assign grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start = grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg;

assign grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg;

assign x_address0 = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_address0;

assign x_ce0 = grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_ce0;

assign y_address1 = grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address1;

endmodule //Softmax
