-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ReLU is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    y_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    y_ce0 : OUT STD_LOGIC;
    y_we0 : OUT STD_LOGIC;
    y_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of ReLU is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ReLU_ReLU,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.779286,HLS_SYN_LAT=8005,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=162,HLS_SYN_LUT=554,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1F40 : STD_LOGIC_VECTOR (12 downto 0) := "1111101000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv10_190 : STD_LOGIC_VECTOR (9 downto 0) := "0110010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln9_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln10_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_508 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln10_fu_292_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln10_reg_516 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln12_1_fu_312_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln12_1_reg_521 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln12_fu_318_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln12_reg_526 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln12_5_fu_376_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln12_5_reg_531 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln12_5_reg_531_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln12_fu_461_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln12_reg_541 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal k_fu_86 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln11_fu_322_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal j_fu_90 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln10_1_fu_300_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_94 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln10_2_fu_187_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (9 downto 0);
    signal i_fu_98 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln9_1_fu_227_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten13_fu_102 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln9_1_fu_166_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_indvar_flatten13_load : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln10_1_fu_181_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln9_fu_214_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_234_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_3_fu_246_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln12_fu_242_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln12_1_fu_254_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln11_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln9_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_fu_220_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln9_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln10_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_281_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln12_fu_258_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln12_2_fu_308_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_1_fu_350_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl_cast_fu_343_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln12_3_fu_357_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln12_2_fu_361_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln12_4_fu_367_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln12_3_fu_370_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_fu_385_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_395_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln1018_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1018_1_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ymaggreater_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln12_fu_381_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln25_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_fu_435_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1018_2_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1022_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln25_fu_443_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln18_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln12_1_fu_457_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_119 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component ReLU_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component ReLU_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    i_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    i_fu_98 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_fu_98 <= select_ln9_1_fu_227_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten13_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_119)) then
                if ((icmp_ln9_fu_160_p2 = ap_const_lv1_0)) then 
                    indvar_flatten13_fu_102 <= add_ln9_1_fu_166_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten13_fu_102 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_119)) then
                if ((icmp_ln9_fu_160_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_94 <= select_ln10_2_fu_187_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_94 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    j_fu_90 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_90 <= select_ln10_1_fu_300_p3;
                end if;
            end if; 
        end if;
    end process;

    k_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
                    k_fu_86 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    k_fu_86 <= add_ln11_fu_322_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln12_1_reg_521 <= add_ln12_1_fu_312_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln10_reg_516 <= select_ln10_fu_292_p3;
                trunc_ln12_reg_526 <= trunc_ln12_fu_318_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                select_ln12_reg_541 <= select_ln12_fu_461_p3;
                    zext_ln12_5_reg_531(12 downto 0) <= zext_ln12_5_fu_376_p1(12 downto 0);
                    zext_ln12_5_reg_531_pp0_iter3_reg(12 downto 0) <= zext_ln12_5_reg_531(12 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_160_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln10_reg_508 <= icmp_ln10_fu_175_p2;
            end if;
        end if;
    end process;
    zext_ln12_5_reg_531(63 downto 13) <= "000000000000000000000000000000000000000000000000000";
    zext_ln12_5_reg_531_pp0_iter3_reg(63 downto 13) <= "000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln10_1_fu_181_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv10_1));
    add_ln10_fu_281_p2 <= std_logic_vector(unsigned(select_ln9_fu_220_p3) + unsigned(ap_const_lv5_1));
    add_ln11_fu_322_p2 <= std_logic_vector(unsigned(select_ln10_fu_292_p3) + unsigned(ap_const_lv5_1));
    add_ln12_1_fu_312_p2 <= std_logic_vector(unsigned(add_ln12_fu_258_p2) + unsigned(zext_ln12_2_fu_308_p1));
    add_ln12_2_fu_361_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_343_p3) + unsigned(zext_ln12_3_fu_357_p1));
    add_ln12_3_fu_370_p2 <= std_logic_vector(unsigned(add_ln12_2_fu_361_p2) + unsigned(zext_ln12_4_fu_367_p1));
    add_ln12_fu_258_p2 <= std_logic_vector(unsigned(zext_ln12_fu_242_p1) + unsigned(zext_ln12_1_fu_254_p1));
    add_ln9_1_fu_166_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten13_load) + unsigned(ap_const_lv13_1));
    add_ln9_fu_214_p2 <= std_logic_vector(unsigned(i_fu_98) + unsigned(ap_const_lv5_1));
    and_ln18_fu_451_p2 <= (xor_ln1022_fu_423_p2 and icmp_ln1018_2_fu_417_p2);
    and_ln25_fu_411_p2 <= (icmp_ln1018_fu_399_p2 and icmp_ln1018_1_fu_405_p2);
    and_ln9_fu_275_p2 <= (xor_ln9_fu_264_p2 and icmp_ln11_fu_269_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_119_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_119 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln9_fu_160_p2)
    begin
        if (((icmp_ln9_fu_160_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;
    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten13_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten13_fu_102)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten13_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_indvar_flatten13_load <= indvar_flatten13_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_94)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_94;
        end if; 
    end process;

    bitcast_ln12_1_fu_457_p1 <= select_ln25_fu_443_p3;
    bitcast_ln12_fu_381_p1 <= x_q0;
    icmp_ln1018_1_fu_405_p2 <= "1" when (tmp_4_fu_395_p1 = ap_const_lv52_0) else "0";
    icmp_ln1018_2_fu_417_p2 <= "1" when (tmp_fu_385_p4 = ap_const_lv11_7FF) else "0";
    icmp_ln1018_fu_399_p2 <= "1" when (tmp_fu_385_p4 = ap_const_lv11_0) else "0";
    icmp_ln10_fu_175_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv10_190) else "0";
    icmp_ln11_fu_269_p2 <= "1" when (k_fu_86 = ap_const_lv5_14) else "0";
    icmp_ln9_fu_160_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten13_load = ap_const_lv13_1F40) else "0";
    or_ln10_fu_287_p2 <= (icmp_ln10_reg_508 or and_ln9_fu_275_p2);
    p_shl_cast_fu_343_p3 <= (trunc_ln12_reg_526 & ap_const_lv4_0);
    res_fu_435_p3 <= 
        bitcast_ln12_fu_381_p1 when (ymaggreater_fu_429_p2(0) = '1') else 
        ap_const_lv64_0;
    select_ln10_1_fu_300_p3 <= 
        add_ln10_fu_281_p2 when (and_ln9_fu_275_p2(0) = '1') else 
        select_ln9_fu_220_p3;
    select_ln10_2_fu_187_p3 <= 
        ap_const_lv10_1 when (icmp_ln10_fu_175_p2(0) = '1') else 
        add_ln10_1_fu_181_p2;
    select_ln10_fu_292_p3 <= 
        ap_const_lv5_0 when (or_ln10_fu_287_p2(0) = '1') else 
        k_fu_86;
    select_ln12_fu_461_p3 <= 
        ap_const_lv64_0 when (and_ln18_fu_451_p2(0) = '1') else 
        bitcast_ln12_1_fu_457_p1;
    select_ln25_fu_443_p3 <= 
        bitcast_ln12_fu_381_p1 when (and_ln25_fu_411_p2(0) = '1') else 
        res_fu_435_p3;
    select_ln9_1_fu_227_p3 <= 
        add_ln9_fu_214_p2 when (icmp_ln10_reg_508(0) = '1') else 
        i_fu_98;
    select_ln9_fu_220_p3 <= 
        ap_const_lv5_0 when (icmp_ln10_reg_508(0) = '1') else 
        j_fu_90;
    tmp_1_fu_350_p3 <= (add_ln12_1_reg_521 & ap_const_lv2_0);
    tmp_2_fu_234_p3 <= (select_ln9_1_fu_227_p3 & ap_const_lv4_0);
    tmp_3_fu_246_p3 <= (select_ln9_1_fu_227_p3 & ap_const_lv2_0);
    tmp_4_fu_395_p1 <= x_q0(52 - 1 downto 0);
    tmp_fu_385_p4 <= x_q0(62 downto 52);
    trunc_ln12_fu_318_p1 <= add_ln12_1_fu_312_p2(9 - 1 downto 0);
    x_address0 <= zext_ln12_5_fu_376_p1(13 - 1 downto 0);

    x_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            x_ce0 <= ap_const_logic_1;
        else 
            x_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln1022_fu_423_p2 <= (icmp_ln1018_1_fu_405_p2 xor ap_const_lv1_1);
    xor_ln9_fu_264_p2 <= (icmp_ln10_reg_508 xor ap_const_lv1_1);
    y_address0 <= zext_ln12_5_reg_531_pp0_iter3_reg(13 - 1 downto 0);

    y_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            y_ce0 <= ap_const_logic_1;
        else 
            y_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    y_d0 <= select_ln12_reg_541;

    y_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            y_we0 <= ap_const_logic_1;
        else 
            y_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ymaggreater_fu_429_p2 <= "1" when (signed(x_q0) > signed(ap_const_lv64_0)) else "0";
    zext_ln12_1_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_246_p3),10));
    zext_ln12_2_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_1_fu_300_p3),10));
    zext_ln12_3_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_350_p3),13));
    zext_ln12_4_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_reg_516),13));
    zext_ln12_5_fu_376_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln12_3_fu_370_p2),64));
    zext_ln12_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_234_p3),10));
end behav;
