-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ReLU is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of ReLU is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ReLU_ReLU,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.425083,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=138,HLS_SYN_LUT=1382,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv52_0 : STD_LOGIC_VECTOR (51 downto 0) := "0000000000000000000000000000000000000000000000000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_66_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_assign_reg_292 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_Result_s_reg_299 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal tmp_5_fu_173_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_5_reg_304 : STD_LOGIC_VECTOR (51 downto 0);
    signal isNeg_fu_187_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_309 : STD_LOGIC_VECTOR (0 downto 0);
    signal ush_fu_205_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ush_reg_314 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_V_fu_70_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_fu_73_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_83_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln1018_fu_87_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1018_1_fu_93_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ymaggreater_fu_117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln25_fu_99_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_fu_123_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1018_2_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1022_fu_111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln25_fu_130_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal and_ln18_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bitcast_ln486_fu_143_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_V_1_fu_147_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_fu_163_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln513_fu_177_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln513_fu_181_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln1364_fu_195_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1364_fu_201_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal mantissa_fu_213_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal sext_ln1340_fu_226_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_222_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln1340_fu_229_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal r_V_fu_233_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_fu_245_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_1_fu_239_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal zext_ln671_fu_253_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_257_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_267_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_V_2_fu_274_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ReLU_sitodp_32ns_64_6_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    sitodp_32ns_64_6_no_dsp_1_U1 : component ReLU_sitodp_32ns_64_6_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x,
        ce => ap_const_logic_1,
        dout => grp_fu_66_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                isNeg_reg_309 <= add_ln513_fu_181_p2(11 downto 11);
                p_Result_s_reg_299 <= data_V_1_fu_147_p3(63 downto 63);
                tmp_5_reg_304 <= tmp_5_fu_173_p1;
                ush_reg_314 <= ush_fu_205_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                y_assign_reg_292 <= grp_fu_66_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln513_fu_181_p2 <= std_logic_vector(unsigned(zext_ln513_fu_177_p1) + unsigned(ap_const_lv12_C01));
    and_ln18_fu_137_p2 <= (xor_ln1022_fu_111_p2 and icmp_ln1018_2_fu_105_p2);
    and_ln25_fu_99_p2 <= (icmp_ln1018_fu_87_p2 and icmp_ln1018_1_fu_93_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;

    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        result_V_2_fu_274_p2 when (p_Result_s_reg_299(0) = '1') else 
        val_fu_267_p3;
    bitcast_ln486_fu_143_p1 <= select_ln25_fu_130_p3;
    data_V_1_fu_147_p3 <= 
        ap_const_lv64_0 when (and_ln18_fu_137_p2(0) = '1') else 
        bitcast_ln486_fu_143_p1;
    data_V_fu_70_p1 <= y_assign_reg_292;
    icmp_ln1018_1_fu_93_p2 <= "1" when (tmp_3_fu_83_p1 = ap_const_lv52_0) else "0";
    icmp_ln1018_2_fu_105_p2 <= "1" when (tmp_2_fu_73_p4 = ap_const_lv11_7FF) else "0";
    icmp_ln1018_fu_87_p2 <= "1" when (tmp_2_fu_73_p4 = ap_const_lv11_0) else "0";
    isNeg_fu_187_p3 <= add_ln513_fu_181_p2(11 downto 11);
    mantissa_fu_213_p4 <= ((ap_const_lv1_1 & tmp_5_reg_304) & ap_const_lv1_0);
    r_V_1_fu_239_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_222_p1),to_integer(unsigned('0' & zext_ln1340_fu_229_p1(31-1 downto 0)))));
    r_V_fu_233_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_222_p1),to_integer(unsigned('0' & zext_ln1340_fu_229_p1(31-1 downto 0)))));
    res_fu_123_p3 <= 
        y_assign_reg_292 when (ymaggreater_fu_117_p2(0) = '1') else 
        ap_const_lv64_0;
    result_V_2_fu_274_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_267_p3));
    select_ln25_fu_130_p3 <= 
        y_assign_reg_292 when (and_ln25_fu_99_p2(0) = '1') else 
        res_fu_123_p3;
        sext_ln1340_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ush_reg_314),32));

        sext_ln1364_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1364_fu_195_p2),12));

    sub_ln1364_fu_195_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(tmp_4_fu_163_p4));
    tmp_1_fu_257_p4 <= r_V_1_fu_239_p2(84 downto 53);
    tmp_2_fu_73_p4 <= data_V_fu_70_p1(62 downto 52);
    tmp_3_fu_83_p1 <= data_V_fu_70_p1(52 - 1 downto 0);
    tmp_4_fu_163_p4 <= data_V_1_fu_147_p3(62 downto 52);
    tmp_5_fu_173_p1 <= data_V_1_fu_147_p3(52 - 1 downto 0);
    tmp_fu_245_p3 <= r_V_fu_233_p2(53 downto 53);
    ush_fu_205_p3 <= 
        sext_ln1364_fu_201_p1 when (isNeg_fu_187_p3(0) = '1') else 
        add_ln513_fu_181_p2;
    val_fu_267_p3 <= 
        zext_ln671_fu_253_p1 when (isNeg_reg_309(0) = '1') else 
        tmp_1_fu_257_p4;
    xor_ln1022_fu_111_p2 <= (icmp_ln1018_1_fu_93_p2 xor ap_const_lv1_1);
    ymaggreater_fu_117_p2 <= "1" when (signed(data_V_fu_70_p1) > signed(ap_const_lv64_0)) else "0";
    zext_ln1340_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1340_fu_226_p1),137));
    zext_ln15_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_213_p4),137));
    zext_ln513_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_163_p4),12));
    zext_ln671_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_245_p3),32));
end behav;
