-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Softmax is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    y_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    y_ce0 : OUT STD_LOGIC;
    y_we0 : OUT STD_LOGIC;
    y_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    y_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    y_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    y_ce1 : OUT STD_LOGIC;
    y_q1 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of Softmax is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Softmax_Softmax,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.059000,HLS_SYN_LAT=131,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2846,HLS_SYN_LUT=3809,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal y_load_reg_90 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal b_y_fu_71_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal b_y_reg_95 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_idle : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_ready : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_ce0 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_idle : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_ready : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out_ap_vld : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_idle : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_ready : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1 : STD_LOGIC;
    signal grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Softmax_Softmax_Pipeline_VITIS_LOOP_10_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        y_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y_ce0 : OUT STD_LOGIC;
        y_we0 : OUT STD_LOGIC;
        y_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component Softmax_Softmax_Pipeline_VITIS_LOOP_14_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        b_y : IN STD_LOGIC_VECTOR (63 downto 0);
        y_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y_ce0 : OUT STD_LOGIC;
        y_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
        b_y_1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        b_y_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Softmax_Softmax_Pipeline_VITIS_LOOP_17_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        y_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y_ce0 : OUT STD_LOGIC;
        y_we0 : OUT STD_LOGIC;
        y_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        y_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        y_ce1 : OUT STD_LOGIC;
        y_q1 : IN STD_LOGIC_VECTOR (63 downto 0);
        b_y_1_reload : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48 : component Softmax_Softmax_Pipeline_VITIS_LOOP_10_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start,
        ap_done => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done,
        ap_idle => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_idle,
        ap_ready => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_ready,
        x_address0 => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_address0,
        x_ce0 => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_ce0,
        x_q0 => x_q0,
        y_address0 => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0,
        y_ce0 => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0,
        y_we0 => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0,
        y_d0 => grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0);

    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56 : component Softmax_Softmax_Pipeline_VITIS_LOOP_14_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start,
        ap_done => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done,
        ap_idle => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_idle,
        ap_ready => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_ready,
        b_y => b_y_reg_95,
        y_address0 => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0,
        y_ce0 => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0,
        y_q0 => y_q0,
        b_y_1_out => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out,
        b_y_1_out_ap_vld => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out_ap_vld);

    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64 : component Softmax_Softmax_Pipeline_VITIS_LOOP_17_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start,
        ap_done => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done,
        ap_idle => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_idle,
        ap_ready => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_ready,
        y_address0 => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0,
        y_ce0 => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0,
        y_we0 => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0,
        y_d0 => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0,
        y_address1 => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address1,
        y_ce1 => grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1,
        y_q1 => y_q1,
        b_y_1_reload => grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_b_y_1_out);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_ready = ap_const_logic_1)) then 
                    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_ready = ap_const_logic_1)) then 
                    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                b_y_reg_95 <= b_y_fu_71_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                y_load_reg_90 <= y_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done, grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done, grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done)
    begin
        if ((grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done)
    begin
        if ((grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done)
    begin
        if ((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done, ap_CS_fsm_state8)
    begin
        if (((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;

    ap_ready_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done, ap_CS_fsm_state8)
    begin
        if (((grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    b_y_fu_71_p1 <= y_load_reg_90;
    grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_ap_start_reg;
    grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start <= grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_ap_start_reg;
    grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_ap_start_reg;
    x_address0 <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_address0;
    x_ce0 <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_x_ce0;

    y_address0_assign_proc : process(ap_CS_fsm_state3, grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0, grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0, grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_address0 <= ap_const_lv64_0(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            y_address0 <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            y_address0 <= grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y_address0 <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_address0;
        else 
            y_address0 <= "XXXX";
        end if; 
    end process;

    y_address1 <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_address1;

    y_ce0_assign_proc : process(ap_CS_fsm_state3, grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0, grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0, grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            y_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            y_ce0 <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            y_ce0 <= grp_Softmax_Pipeline_VITIS_LOOP_14_2_fu_56_y_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y_ce0 <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_ce0;
        else 
            y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y_ce1_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            y_ce1 <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_ce1;
        else 
            y_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    y_d0_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0, grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0, ap_CS_fsm_state2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            y_d0 <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y_d0 <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_d0;
        else 
            y_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    y_we0_assign_proc : process(grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0, grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0, ap_CS_fsm_state2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            y_we0 <= grp_Softmax_Pipeline_VITIS_LOOP_17_3_fu_64_y_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y_we0 <= grp_Softmax_Pipeline_VITIS_LOOP_10_1_fu_48_y_we0;
        else 
            y_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
